/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.desafio1;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author andersonr
 */
public class ConversionCalculatorWindow extends javax.swing.JFrame {

    /**
     * Creates new form ConversionCalculatorWindow
     */
    public ConversionCalculatorWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        textInput = new javax.swing.JTextField();
        optionBin = new javax.swing.JRadioButton();
        optionOct = new javax.swing.JRadioButton();
        optionDec = new javax.swing.JRadioButton();
        optionHex = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textOutput = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textInputActionPerformed(evt);
            }
        });

        buttonGroup1.add(optionBin);
        optionBin.setText("BIN");
        optionBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionBinActionPerformed(evt);
            }
        });

        buttonGroup1.add(optionOct);
        optionOct.setText("OCT");

        buttonGroup1.add(optionDec);
        optionDec.setText("DEC");

        buttonGroup1.add(optionHex);
        optionHex.setText("HEX");

        textOutput.setColumns(20);
        textOutput.setRows(5);
        jScrollPane1.setViewportView(textOutput);

        jButton1.setText("Executar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(optionBin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionOct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionDec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionHex)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionBin)
                    .addComponent(optionOct)
                    .addComponent(optionDec)
                    .addComponent(optionHex))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optionBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionBinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionBinActionPerformed

    private void textInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textInputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String output = "";
        
        Calculator calculator = new ConversionCalculator();
        List<Object> cmd = new ArrayList<>();
        
        cmd.add(new Integer(ConversionCalculator.BIN));
        cmd.add(new Integer(ConversionCalculator.OCT));            
        cmd.add(textInput.getText());
            
        if (this.optionBin.isSelected()) {
            cmd.set(0, new Integer(ConversionCalculator.BIN));
        } else if (this.optionOct.isSelected()) {
            cmd.set(0, new Integer(ConversionCalculator.OCT));
        } else if (this.optionDec.isSelected()) {
            cmd.set(0, new Integer(ConversionCalculator.DEC));
        } else if (this.optionHex.isSelected()) {
            cmd.set(0, new Integer(ConversionCalculator.HEX));
        }
        
        if (!this.optionBin.isSelected()) {
            cmd.set(1, new Integer(ConversionCalculator.BIN));
            output += "BIN: " + calculator.execute(cmd) + "\n";
        } 
        
        if (!this.optionOct.isSelected()) {
            cmd.set(1, new Integer(ConversionCalculator.OCT));
            output += "OCT: " + calculator.execute(cmd) + "\n";
        }
        
        if (!this.optionDec.isSelected()) {
            cmd.set(1, new Integer(ConversionCalculator.DEC));
            output += "DEC: " + calculator.execute(cmd) + "\n";
        }
        
        if (!this.optionHex.isSelected()) {
            cmd.set(1, new Integer(ConversionCalculator.HEX));
            output += "HEX: " + calculator.execute(cmd) + "\n";
        }
        
        textOutput.setText(output);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversionCalculatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversionCalculatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversionCalculatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversionCalculatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversionCalculatorWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton optionBin;
    private javax.swing.JRadioButton optionDec;
    private javax.swing.JRadioButton optionHex;
    private javax.swing.JRadioButton optionOct;
    private javax.swing.JTextField textInput;
    private javax.swing.JTextArea textOutput;
    // End of variables declaration//GEN-END:variables
}
